from typing import Any, Protocol

class Connection(Protocol):
    async def execute(self, *args: Any, **kwargs: Any) -> Any: ...
    async def executemany(self, *args: Any, **kwargs: Any) -> Any: ...
    async def executescript(self, *args: Any, **kwargs: Any) -> Any: ...
    async def commit(self) -> None: ...
    async def rollback(self) -> None: ...
    @property
    def in_transaction(self) -> bool: ...
    async def close(self) -> None: ...
