root      ::= text "<meta>" obj "</meta>"
text      ::= (anychar)*
anychar  ::= [^<] | "<" [^m] | "<m" [^e] | "<me" [^t] | "<met" [^a] | "<meta" [^>]
quote     ::= "\""

string    ::= quote (char)* quote
char      ::= [^"\\] | "\\" ["\\/bfnrt]

emoji     ::= quote ([😀-🙏] | [🚀-🛀] | [🌀-🗿]) quote
keyword   ::= quote "#" [a-zA-Z0-9-]+ quote
kwarray   ::= "[" (keyword ("," keyword){0,2})? "]"

obj       ::= "{" quote "emoji" quote ": " emoji "," quote "keywords" quote ": " kwarray "}"
