from zxcvbn.scoring import ALL_UPPER as ALL_UPPER, START_UPPER as START_UPPER

def get_feedback(score, sequence): ...
def get_match_feedback(match, is_sole_match): ...
def get_dictionary_match_feedback(match, is_sole_match): ...
