from .adjacency_graphs import ADJACENCY_GRAPHS as ADJACENCY_GRAPHS
from _typeshed import Incomplete

def calc_average_degree(graph): ...

BRUTEFORCE_CARDINALITY: int
MIN_GUESSES_BEFORE_GROWING_SEQUENCE: int
MIN_SUBMATCH_GUESSES_SINGLE_CHAR: int
MIN_SUBMATCH_GUESSES_MULTI_CHAR: int
MIN_YEAR_SPACE: int
REFERENCE_YEAR: int

def nCk(n, k): ...
def most_guessable_match_sequence(password, matches, _exclude_additive: bool = False): ...
def estimate_guesses(match, password): ...
def bruteforce_guesses(match): ...
def dictionary_guesses(match): ...
def repeat_guesses(match): ...
def sequence_guesses(match): ...
def regex_guesses(match): ...
def date_guesses(match): ...

KEYBOARD_AVERAGE_DEGREE: Incomplete
KEYPAD_AVERAGE_DEGREE: Incomplete
KEYBOARD_STARTING_POSITIONS: Incomplete
KEYPAD_STARTING_POSITIONS: Incomplete

def spatial_guesses(match): ...

START_UPPER: Incomplete
END_UPPER: Incomplete
ALL_UPPER: Incomplete
ALL_LOWER: Incomplete

def uppercase_variations(match): ...
def l33t_variations(match): ...
